### ISSUE TITLE
No forced auto-updates please

### ISSUE THREAD

**Issue by Git3746** [goaaats/FFXIVQuickLauncher#141]
Multiple times I've had to troubleshoot some issue after a forced auto update that I can't disable. Now with the latest update I'm forced to find and install some windows update and restart my pc just so I can launch the setup.exe with useless desktop shortcuts instead of having a standalone program.

I don't want to update. Is there a possibility for such an option?

**Comment by goaaats** [comment]
While the last few updates have been prone to break, due to the settings change and updater, you can download artifacts that do not update by themselves.

I DON'T recommend this however since then, you won't receive fixes for login issues and game updates.


As for the windows update, raising the .NET version is something I wanted to do for a while now and as things evolve and time goes on frameworks get updated.
