### ISSUE TITLE
Duty Roulette checker not working?

### ISSUE THREAD

**Issue by TheMiketroid** [goaaats/FFXIVQuickLauncher#193]
Every time I queue for a roulette, rather than displaying the specific instance that was selected, it shows up in the in-game chat as "Duty Pop: Duty Roulette", rather than the specific raid/dungeon. Queuing for a specific raid however displays the proper name. (if I queue for, say, Ifrit normal, it would display as "Duty Pop: The Bowl of Embers")

This issue has been happening since the 5.2 patch and the launchers subsequent updates.

**Comment by ff-meli** [comment]
This is because SE removed the information about the duty from the network packets that are sent, for roulettes only.  There is no longer any way to get that information, so the display was changed to just be "Duty Roulette", because some people still wanted the notification, rather than just removing it entirely.
