### ISSUE TITLE
Welcome back, same old problem.

### ISSUE THREAD

**Issue by Kumicoo** [goaaats/FFXIVQuickLauncher#76]
/xlhelp doesnt work once again. Please fix. the whole launcher ingame functions are broken.

**Comment by DJScias** [comment]
Going to guess this is because the 5.05 definitions weren't added to Nhaama yet: https://github.com/goaaats/Nhaama/tree/master/definitions/FFXIV/dx11

Generally I've noticed once they're created that all the functions of the launcher magically start working (they probably need the definitions to inject itself).

**Comment by Kumicoo** [comment]
Guess no fix coming soon

**Comment by DJScias** [comment]
Yep, seems like there's still an issue with it.

**Comment by NLDGreen** [comment]
/xlhelp and /xlbotjoin both don't work, even though I got my own discord bot in my server

**Comment by goaaats** [comment]
Should be fixed
