### ISSUE TITLE
Steam Link not registering input

### ISSUE THREAD

**Issue by hlouzan** [goaaats/FFXIVQuickLauncher#93]
Not sure if its a FFXIVQuickLauncher issue or not but when I open the game with it when I connect remotely with Steam Link the game doesn't recognize any keyboard/mouse/gamepad inputs while if I launch the game normally without FFXIVQuickLauncher it does recognize inputs.

**Comment by LinosM** [comment]
Pretty sure it's an issue with the launcher itself. My Discord hotkeys (push to talk, toggle mute, etc.) doesn't work when FFXIV is in focus, but it does work when I don't use the launcher.

I also use a program to translate piano keys into keyboard inputs for the Bard performance and that doesn't work either when running with the launcher.

**Comment by Zyian** [comment]
This could happen when the programs and the game are not at the same permission level. Say if the game is launched as admin while Discord, Piano keys, etc are not then this could prevent the keys from being recognized. Ensure that the launcher is not being ran as admin (because this would cause the game to be launched as admin)

**Comment by Aida-Enna** [comment]
@hlouzan Did you ever get it fixed?

**Comment by hlouzan** [comment]
I vaguely remember not managing to fix it sorry, I haven't played the last few months.

**Comment by Aida-Enna** [comment]
No worries, thanks for responding! I'll go ahead and close it and feel free to comment/create a new issue when/if you come back and it's still an issue.

**Comment by hlouzan** [comment]
Sure no problem, thanks for the follow up.
